parser: babel-eslint
env:
    mocha: true
extends:
    - eslint-config-airbnb
    - eslint:recommended
    - plugin:import/errors
    - plugin:import/warnings
plugins:
    - standard
    - promise
rules:
    arrow-parens: 0
    eqeqeq: 0
    no-return-assign: 0
    semi: [2, always]
    space-before-function-paren: [2, {"anonymous": "never", "named": "never", "asyncArrow": "ignore"}]
    yoda: 0
    arrow-spacing: 2
    dot-location: [2, "property"]
    no-console: 2
    no-var: 0
    no-undef: 0
    camelcase: 2
    indent: [2, 4]
    key-spacing: [0, {"align": "colon"}]
    import/no-dynamic-require: 0
    import/no-extraneous-dependencies: 0
    react/prefer-stateless-function: 0
    react/forbid-prop-types: 0
    react/prop-types: 0
    react/jsx-indent-props: [2, 4]
    react/jsx-filename-extension: 0
    react/jsx-no-target-blank: 0
    react/require-extension: 0
    react/self-closing-comp: 0
    react/no-array-index-key: 0
    react/jsx-indent: [0, "tab"]
    react/jsx-tag-spacing: 0
    react/jsx-max-props-per-line: 0
    react/jsx-first-prop-new-line: [0, "multiline"]
